### ISSUE TITLE
Crash when animation ends

### ISSUE THREAD

**Issue by BrittleFoot** [niemandkun/adddxdx#11]
This works fine,
```Java
addComponent(Animator
                .ofFloat(y -> getTransform().setLocation(2.5f, y, 2.5f))
                .from(1f).to(1.2f).in(Duration.ofSeconds(1))
                .repeatIn(Duration.ofSeconds(1))
                .build());
```

but when you turn off `repeat` sentence, program fails with `ConcurrentModificationException` after `1` second (animation duration)
```Java
addComponent(Animator
                .ofFloat(y -> getTransform().setLocation(2.5f, y, 2.5f))
                .from(1f).to(1.2f).in(Duration.ofSeconds(1))
                //.repeatIn(Duration.ofSeconds(1))
                .build());
```
Stacktrace
```
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at org.adddxdx.clocks.TicksMeasureSystem.update(TicksMeasureSystem.java:45)
	at org.adddxdx.engine.ActiveSystem.fixedUpdate(ActiveSystem.java:34)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.adddxdx.engine.Story.reveal(Story.java:45)
	at org.adddxdx.briefexample.EntryPoint.main(EntryPoint.java:34)
```

**Comment by BrittleFoot** [comment]
seat of the trouble:

[`getActor().removeComponent(this);`](https://github.com/niemandkun/adddxdx/blob/3a082c97c34bd307935fd2b534a2f28266f0526a/src/main/java/org/adddxdx/clocks/Animator.java#L93)
